source "https://rubygems.org"

ruby "2.3.0"

gem "activesupport"
gem "cheesy-common", :github => "Team254/cheesy-common"
gem "daemons"
gem "dedent"
gem "httparty"
gem "mysql2"
gem "pathological"
gem "pony"
gem "rake"
gem "sequel"
gem "sinatra"
gem "thin"
